const ruleItemsData = [
    {
        "id": 0,
        "tags": "['l1']",
        "acc": 0.735,
        "precision": 0.847,
        "recall": 0.789,
        "statistical_parity_difference": -0.137,
        "equal_opportunity_difference": -0.106,
        "disparate_impact": 0.82,
        "error_rate_ratio": 0.115
    },
    {
        "id": 1,
        "tags": "['l2']",
        "acc": 0.752,
        "precision": 0.848,
        "recall": 0.814,
        "statistical_parity_difference": -0.201,
        "equal_opportunity_difference": -0.168,
        "disparate_impact": 0.744,
        "error_rate_ratio": 0.097
    },
    {
        "id": 2,
        "tags": "['max']",
        "acc": 0.751,
        "precision": 0.846,
        "recall": 0.813,
        "statistical_parity_difference": -0.231,
        "equal_opportunity_difference": -0.181,
        "disparate_impact": 0.711,
        "error_rate_ratio": 0.103
    },
    {
        "id": 3,
        "tags": "['PCA3']",
        "acc": 0.741,
        "precision": 0.858,
        "recall": 0.795,
        "statistical_parity_difference": -0.154,
        "equal_opportunity_difference": -0.189,
        "disparate_impact": 0.808,
        "error_rate_ratio": 0.168
    },
    {
        "id": 4,
        "tags": "['PCA5']",
        "acc": 0.723,
        "precision": 0.819,
        "recall": 0.795,
        "statistical_parity_difference": -0.169,
        "equal_opportunity_difference": -0.145,
        "disparate_impact": 0.779,
        "error_rate_ratio": 0.096
    },
    {
        "id": 5,
        "tags": "['reweighing']",
        "acc": 0.727,
        "precision": 0.839,
        "recall": 0.783,
        "statistical_parity_difference": -0.155,
        "equal_opportunity_difference": -0.181,
        "disparate_impact": 0.8,
        "error_rate_ratio": 0.081
    },
    {
        "id": 6,
        "tags": "['DisparateImpactRemover']",
        "acc": 0.734,
        "precision": 0.829,
        "recall": 0.804,
        "statistical_parity_difference": -0.094,
        "equal_opportunity_difference": -0.121,
        "disparate_impact": 0.879,
        "error_rate_ratio": 0.126
    },
    {
        "id": 7,
        "tags": "['l1', 'PCA3']",
        "acc": 0.743,
        "precision": 0.853,
        "recall": 0.797,
        "statistical_parity_difference": -0.161,
        "equal_opportunity_difference": -0.139,
        "disparate_impact": 0.797,
        "error_rate_ratio": 0.112
    },
    {
        "id": 8,
        "tags": "['l1', 'PCA5']",
        "acc": 0.727,
        "precision": 0.854,
        "recall": 0.77,
        "statistical_parity_difference": -0.232,
        "equal_opportunity_difference": -0.176,
        "disparate_impact": 0.71,
        "error_rate_ratio": 0.069
    },
    {
        "id": 9,
        "tags": "['l2', 'PCA3']",
        "acc": 0.747,
        "precision": 0.849,
        "recall": 0.799,
        "statistical_parity_difference": -0.173,
        "equal_opportunity_difference": -0.128,
        "disparate_impact": 0.778,
        "error_rate_ratio": 0.091
    },
    {
        "id": 10,
        "tags": "['l2', 'PCA5']",
        "acc": 0.72,
        "precision": 0.835,
        "recall": 0.778,
        "statistical_parity_difference": -0.113,
        "equal_opportunity_difference": -0.071,
        "disparate_impact": 0.854,
        "error_rate_ratio": 0.076
    },
    {
        "id": 11,
        "tags": "['max', 'PCA3']",
        "acc": 0.745,
        "precision": 0.86,
        "recall": 0.792,
        "statistical_parity_difference": -0.211,
        "equal_opportunity_difference": -0.179,
        "disparate_impact": 0.737,
        "error_rate_ratio": 0.121
    },
    {
        "id": 12,
        "tags": "['max', 'PCA5']",
        "acc": 0.728,
        "precision": 0.834,
        "recall": 0.791,
        "statistical_parity_difference": -0.146,
        "equal_opportunity_difference": -0.092,
        "disparate_impact": 0.811,
        "error_rate_ratio": 0.096
    },
    {
        "id": 13,
        "tags": "['l1', 'reweighing']",
        "acc": 0.736,
        "precision": 0.838,
        "recall": 0.799,
        "statistical_parity_difference": -0.124,
        "equal_opportunity_difference": -0.135,
        "disparate_impact": 0.841,
        "error_rate_ratio": 0.059
    },
    {
        "id": 14,
        "tags": "['l2', 'reweighing']",
        "acc": 0.721,
        "precision": 0.826,
        "recall": 0.79,
        "statistical_parity_difference": -0.134,
        "equal_opportunity_difference": -0.168,
        "disparate_impact": 0.825,
        "error_rate_ratio": 0.091
    },
    {
        "id": 15,
        "tags": "['max', 'reweighing']",
        "acc": 0.749,
        "precision": 0.854,
        "recall": 0.804,
        "statistical_parity_difference": -0.151,
        "equal_opportunity_difference": -0.155,
        "disparate_impact": 0.808,
        "error_rate_ratio": 0.088
    },
    {
        "id": 16,
        "tags": "['l1', 'DisparateImpactRemover']",
        "acc": 0.721,
        "precision": 0.84,
        "recall": 0.777,
        "statistical_parity_difference": -0.071,
        "equal_opportunity_difference": -0.103,
        "disparate_impact": 0.91,
        "error_rate_ratio": 0.136
    },
    {
        "id": 17,
        "tags": "['l2', 'DisparateImpactRemover']",
        "acc": 0.731,
        "precision": 0.848,
        "recall": 0.789,
        "statistical_parity_difference": -0.112,
        "equal_opportunity_difference": -0.076,
        "disparate_impact": 0.858,
        "error_rate_ratio": 0.05
    },
    {
        "id": 18,
        "tags": "['max', 'DisparateImpactRemover']",
        "acc": 0.735,
        "precision": 0.866,
        "recall": 0.78,
        "statistical_parity_difference": -0.093,
        "equal_opportunity_difference": -0.072,
        "disparate_impact": 0.882,
        "error_rate_ratio": 0.076
    },
    {
        "id": 19,
        "tags": "['PCA3', 'l1']",
        "acc": 0.747,
        "precision": 0.855,
        "recall": 0.797,
        "statistical_parity_difference": -0.182,
        "equal_opportunity_difference": -0.147,
        "disparate_impact": 0.767,
        "error_rate_ratio": 0.088
    },
    {
        "id": 20,
        "tags": "['PCA3', 'l2']",
        "acc": 0.734,
        "precision": 0.844,
        "recall": 0.789,
        "statistical_parity_difference": -0.174,
        "equal_opportunity_difference": -0.105,
        "disparate_impact": 0.776,
        "error_rate_ratio": 0.066
    },
    {
        "id": 21,
        "tags": "['PCA3', 'max']",
        "acc": 0.733,
        "precision": 0.857,
        "recall": 0.778,
        "statistical_parity_difference": -0.149,
        "equal_opportunity_difference": -0.15,
        "disparate_impact": 0.812,
        "error_rate_ratio": 0.119
    },
    {
        "id": 22,
        "tags": "['PCA5', 'l1']",
        "acc": 0.731,
        "precision": 0.864,
        "recall": 0.772,
        "statistical_parity_difference": -0.195,
        "equal_opportunity_difference": -0.16,
        "disparate_impact": 0.761,
        "error_rate_ratio": 0.117
    },
    {
        "id": 23,
        "tags": "['PCA5', 'l2']",
        "acc": 0.741,
        "precision": 0.862,
        "recall": 0.788,
        "statistical_parity_difference": -0.2,
        "equal_opportunity_difference": -0.16,
        "disparate_impact": 0.752,
        "error_rate_ratio": 0.112
    },
    {
        "id": 24,
        "tags": "['PCA5', 'max']",
        "acc": 0.731,
        "precision": 0.832,
        "recall": 0.795,
        "statistical_parity_difference": -0.265,
        "equal_opportunity_difference": -0.267,
        "disparate_impact": 0.662,
        "error_rate_ratio": 0.153
    },
    {
        "id": 25,
        "tags": "['reweighing', 'l1']",
        "acc": 0.717,
        "precision": 0.829,
        "recall": 0.781,
        "statistical_parity_difference": -0.174,
        "equal_opportunity_difference": -0.242,
        "disparate_impact": 0.777,
        "error_rate_ratio": 0.15
    },
    {
        "id": 26,
        "tags": "['reweighing', 'l2']",
        "acc": 0.743,
        "precision": 0.86,
        "recall": 0.79,
        "statistical_parity_difference": -0.113,
        "equal_opportunity_difference": -0.127,
        "disparate_impact": 0.859,
        "error_rate_ratio": 0.04
    },
    {
        "id": 27,
        "tags": "['reweighing', 'max']",
        "acc": 0.751,
        "precision": 0.871,
        "recall": 0.791,
        "statistical_parity_difference": -0.141,
        "equal_opportunity_difference": -0.135,
        "disparate_impact": 0.823,
        "error_rate_ratio": 0.081
    },
    {
        "id": 28,
        "tags": "['reweighing', 'PCA3']",
        "acc": 0.731,
        "precision": 0.839,
        "recall": 0.794,
        "statistical_parity_difference": -0.118,
        "equal_opportunity_difference": -0.154,
        "disparate_impact": 0.845,
        "error_rate_ratio": 0.079
    },
    {
        "id": 29,
        "tags": "['reweighing', 'PCA5']",
        "acc": 0.729,
        "precision": 0.844,
        "recall": 0.787,
        "statistical_parity_difference": -0.157,
        "equal_opportunity_difference": -0.16,
        "disparate_impact": 0.8,
        "error_rate_ratio": 0.058
    },
    {
        "id": 30,
        "tags": "['reweighing', 'DisparateImpactRemover']",
        "acc": 0.725,
        "precision": 0.849,
        "recall": 0.776,
        "statistical_parity_difference": -0.103,
        "equal_opportunity_difference": -0.128,
        "disparate_impact": 0.868,
        "error_rate_ratio": 0.072
    },
    {
        "id": 31,
        "tags": "['DisparateImpactRemover', 'l1']",
        "acc": 0.713,
        "precision": 0.842,
        "recall": 0.763,
        "statistical_parity_difference": -0.073,
        "equal_opportunity_difference": -0.079,
        "disparate_impact": 0.905,
        "error_rate_ratio": 0.117
    },
    {
        "id": 32,
        "tags": "['DisparateImpactRemover', 'l2']",
        "acc": 0.755,
        "precision": 0.869,
        "recall": 0.798,
        "statistical_parity_difference": -0.071,
        "equal_opportunity_difference": -0.061,
        "disparate_impact": 0.908,
        "error_rate_ratio": 0.086
    },
    {
        "id": 33,
        "tags": "['DisparateImpactRemover', 'max']",
        "acc": 0.729,
        "precision": 0.856,
        "recall": 0.773,
        "statistical_parity_difference": -0.109,
        "equal_opportunity_difference": -0.12,
        "disparate_impact": 0.86,
        "error_rate_ratio": 0.136
    },
    {
        "id": 34,
        "tags": "['DisparateImpactRemover', 'PCA3']",
        "acc": 0.733,
        "precision": 0.855,
        "recall": 0.781,
        "statistical_parity_difference": -0.093,
        "equal_opportunity_difference": -0.032,
        "disparate_impact": 0.881,
        "error_rate_ratio": 0.062
    },
    {
        "id": 35,
        "tags": "['DisparateImpactRemover', 'PCA5']",
        "acc": 0.726,
        "precision": 0.853,
        "recall": 0.772,
        "statistical_parity_difference": -0.157,
        "equal_opportunity_difference": -0.144,
        "disparate_impact": 0.801,
        "error_rate_ratio": 0.12
    },
    {
        "id": 36,
        "tags": "['DisparateImpactRemover', 'reweighing']",
        "acc": 0.741,
        "precision": 0.86,
        "recall": 0.789,
        "statistical_parity_difference": -0.016,
        "equal_opportunity_difference": -0.046,
        "disparate_impact": 0.983,
        "error_rate_ratio": 0.052
    },
    {
        "id": 37,
        "tags": "['l1', 'reweighing', 'PCA3']",
        "acc": 0.764,
        "precision": 0.866,
        "recall": 0.812,
        "statistical_parity_difference": -0.166,
        "equal_opportunity_difference": -0.171,
        "disparate_impact": 0.792,
        "error_rate_ratio": 0.099
    },
    {
        "id": 38,
        "tags": "['l1', 'reweighing', 'PCA5']",
        "acc": 0.731,
        "precision": 0.844,
        "recall": 0.791,
        "statistical_parity_difference": -0.138,
        "equal_opportunity_difference": -0.157,
        "disparate_impact": 0.824,
        "error_rate_ratio": 0.066
    },
    {
        "id": 39,
        "tags": "['l2', 'reweighing', 'PCA3']",
        "acc": 0.737,
        "precision": 0.836,
        "recall": 0.799,
        "statistical_parity_difference": -0.159,
        "equal_opportunity_difference": -0.173,
        "disparate_impact": 0.791,
        "error_rate_ratio": 0.077
    },
    {
        "id": 40,
        "tags": "['l2', 'reweighing', 'PCA5']",
        "acc": 0.732,
        "precision": 0.849,
        "recall": 0.782,
        "statistical_parity_difference": -0.193,
        "equal_opportunity_difference": -0.208,
        "disparate_impact": 0.756,
        "error_rate_ratio": 0.084
    },
    {
        "id": 41,
        "tags": "['max', 'reweighing', 'PCA3']",
        "acc": 0.738,
        "precision": 0.841,
        "recall": 0.803,
        "statistical_parity_difference": -0.164,
        "equal_opportunity_difference": -0.171,
        "disparate_impact": 0.793,
        "error_rate_ratio": 0.083
    },
    {
        "id": 42,
        "tags": "['max', 'reweighing', 'PCA5']",
        "acc": 0.739,
        "precision": 0.836,
        "recall": 0.8,
        "statistical_parity_difference": -0.124,
        "equal_opportunity_difference": -0.117,
        "disparate_impact": 0.835,
        "error_rate_ratio": 0.049
    },
    {
        "id": 43,
        "tags": "['l1', 'reweighing', 'DisparateImpactRemover']",
        "acc": 0.732,
        "precision": 0.831,
        "recall": 0.795,
        "statistical_parity_difference": -0.05,
        "equal_opportunity_difference": -0.065,
        "disparate_impact": 0.935,
        "error_rate_ratio": 0.058
    },
    {
        "id": 44,
        "tags": "['l2', 'reweighing', 'DisparateImpactRemover']",
        "acc": 0.729,
        "precision": 0.823,
        "recall": 0.8,
        "statistical_parity_difference": -0.035,
        "equal_opportunity_difference": -0.067,
        "disparate_impact": 0.954,
        "error_rate_ratio": 0.047
    },
    {
        "id": 45,
        "tags": "['max', 'reweighing', 'DisparateImpactRemover']",
        "acc": 0.732,
        "precision": 0.844,
        "recall": 0.788,
        "statistical_parity_difference": -0.069,
        "equal_opportunity_difference": -0.097,
        "disparate_impact": 0.911,
        "error_rate_ratio": 0.082
    },
    {
        "id": 46,
        "tags": "['l1', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.737,
        "precision": 0.842,
        "recall": 0.798,
        "statistical_parity_difference": -0.098,
        "equal_opportunity_difference": -0.117,
        "disparate_impact": 0.873,
        "error_rate_ratio": 0.127
    },
    {
        "id": 47,
        "tags": "['l1', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.753,
        "precision": 0.845,
        "recall": 0.823,
        "statistical_parity_difference": -0.188,
        "equal_opportunity_difference": -0.124,
        "disparate_impact": 0.759,
        "error_rate_ratio": 0.055
    },
    {
        "id": 48,
        "tags": "['l2', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.727,
        "precision": 0.855,
        "recall": 0.772,
        "statistical_parity_difference": -0.089,
        "equal_opportunity_difference": -0.092,
        "disparate_impact": 0.885,
        "error_rate_ratio": 0.134
    },
    {
        "id": 49,
        "tags": "['l2', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.739,
        "precision": 0.845,
        "recall": 0.798,
        "statistical_parity_difference": -0.154,
        "equal_opportunity_difference": -0.111,
        "disparate_impact": 0.801,
        "error_rate_ratio": 0.09
    },
    {
        "id": 50,
        "tags": "['max', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.745,
        "precision": 0.844,
        "recall": 0.804,
        "statistical_parity_difference": -0.113,
        "equal_opportunity_difference": -0.105,
        "disparate_impact": 0.851,
        "error_rate_ratio": 0.103
    },
    {
        "id": 51,
        "tags": "['max', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.735,
        "precision": 0.847,
        "recall": 0.793,
        "statistical_parity_difference": -0.147,
        "equal_opportunity_difference": -0.166,
        "disparate_impact": 0.813,
        "error_rate_ratio": 0.152
    },
    {
        "id": 52,
        "tags": "['l1', 'DisparateImpactRemover', 'reweighing']",
        "acc": 0.747,
        "precision": 0.862,
        "recall": 0.789,
        "statistical_parity_difference": -0.067,
        "equal_opportunity_difference": -0.078,
        "disparate_impact": 0.912,
        "error_rate_ratio": 0.054
    },
    {
        "id": 53,
        "tags": "['l2', 'DisparateImpactRemover', 'reweighing']",
        "acc": 0.737,
        "precision": 0.846,
        "recall": 0.793,
        "statistical_parity_difference": -0.064,
        "equal_opportunity_difference": -0.114,
        "disparate_impact": 0.918,
        "error_rate_ratio": 0.104
    },
    {
        "id": 54,
        "tags": "['max', 'DisparateImpactRemover', 'reweighing']",
        "acc": 0.735,
        "precision": 0.845,
        "recall": 0.785,
        "statistical_parity_difference": -0.081,
        "equal_opportunity_difference": -0.111,
        "disparate_impact": 0.894,
        "error_rate_ratio": 0.054
    },
    {
        "id": 55,
        "tags": "['reweighing', 'l1', 'PCA3']",
        "acc": 0.739,
        "precision": 0.867,
        "recall": 0.78,
        "statistical_parity_difference": -0.169,
        "equal_opportunity_difference": -0.178,
        "disparate_impact": 0.788,
        "error_rate_ratio": 0.089
    },
    {
        "id": 56,
        "tags": "['reweighing', 'l1', 'PCA5']",
        "acc": 0.747,
        "precision": 0.868,
        "recall": 0.787,
        "statistical_parity_difference": -0.127,
        "equal_opportunity_difference": -0.155,
        "disparate_impact": 0.838,
        "error_rate_ratio": 0.097
    },
    {
        "id": 57,
        "tags": "['reweighing', 'l2', 'PCA3']",
        "acc": 0.741,
        "precision": 0.862,
        "recall": 0.782,
        "statistical_parity_difference": -0.112,
        "equal_opportunity_difference": -0.156,
        "disparate_impact": 0.857,
        "error_rate_ratio": 0.082
    },
    {
        "id": 58,
        "tags": "['reweighing', 'l2', 'PCA5']",
        "acc": 0.749,
        "precision": 0.883,
        "recall": 0.781,
        "statistical_parity_difference": -0.155,
        "equal_opportunity_difference": -0.15,
        "disparate_impact": 0.811,
        "error_rate_ratio": 0.08
    },
    {
        "id": 59,
        "tags": "['reweighing', 'max', 'PCA3']",
        "acc": 0.739,
        "precision": 0.841,
        "recall": 0.797,
        "statistical_parity_difference": -0.113,
        "equal_opportunity_difference": -0.157,
        "disparate_impact": 0.853,
        "error_rate_ratio": 0.1
    },
    {
        "id": 60,
        "tags": "['reweighing', 'max', 'PCA5']",
        "acc": 0.758,
        "precision": 0.867,
        "recall": 0.808,
        "statistical_parity_difference": -0.133,
        "equal_opportunity_difference": -0.119,
        "disparate_impact": 0.831,
        "error_rate_ratio": 0.046
    },
    {
        "id": 61,
        "tags": "['reweighing', 'l1', 'DisparateImpactRemover']",
        "acc": 0.751,
        "precision": 0.859,
        "recall": 0.808,
        "statistical_parity_difference": -0.039,
        "equal_opportunity_difference": -0.08,
        "disparate_impact": 0.95,
        "error_rate_ratio": 0.06
    },
    {
        "id": 62,
        "tags": "['reweighing', 'l2', 'DisparateImpactRemover']",
        "acc": 0.735,
        "precision": 0.841,
        "recall": 0.793,
        "statistical_parity_difference": -0.09,
        "equal_opportunity_difference": -0.111,
        "disparate_impact": 0.884,
        "error_rate_ratio": 0.063
    },
    {
        "id": 63,
        "tags": "['reweighing', 'max', 'DisparateImpactRemover']",
        "acc": 0.725,
        "precision": 0.825,
        "recall": 0.791,
        "statistical_parity_difference": -0.054,
        "equal_opportunity_difference": -0.092,
        "disparate_impact": 0.928,
        "error_rate_ratio": 0.057
    },
    {
        "id": 64,
        "tags": "['reweighing', 'PCA3', 'l1']",
        "acc": 0.749,
        "precision": 0.842,
        "recall": 0.811,
        "statistical_parity_difference": -0.127,
        "equal_opportunity_difference": -0.146,
        "disparate_impact": 0.831,
        "error_rate_ratio": 0.066
    },
    {
        "id": 65,
        "tags": "['reweighing', 'PCA3', 'l2']",
        "acc": 0.743,
        "precision": 0.851,
        "recall": 0.797,
        "statistical_parity_difference": -0.129,
        "equal_opportunity_difference": -0.152,
        "disparate_impact": 0.833,
        "error_rate_ratio": 0.092
    },
    {
        "id": 66,
        "tags": "['reweighing', 'PCA3', 'max']",
        "acc": 0.736,
        "precision": 0.848,
        "recall": 0.791,
        "statistical_parity_difference": -0.138,
        "equal_opportunity_difference": -0.15,
        "disparate_impact": 0.823,
        "error_rate_ratio": 0.081
    },
    {
        "id": 67,
        "tags": "['reweighing', 'PCA5', 'l1']",
        "acc": 0.741,
        "precision": 0.85,
        "recall": 0.802,
        "statistical_parity_difference": -0.117,
        "equal_opportunity_difference": -0.156,
        "disparate_impact": 0.85,
        "error_rate_ratio": 0.119
    },
    {
        "id": 68,
        "tags": "['reweighing', 'PCA5', 'l2']",
        "acc": 0.743,
        "precision": 0.842,
        "recall": 0.802,
        "statistical_parity_difference": -0.119,
        "equal_opportunity_difference": -0.157,
        "disparate_impact": 0.843,
        "error_rate_ratio": 0.091
    },
    {
        "id": 69,
        "tags": "['reweighing', 'PCA5', 'max']",
        "acc": 0.73,
        "precision": 0.844,
        "recall": 0.786,
        "statistical_parity_difference": -0.11,
        "equal_opportunity_difference": -0.118,
        "disparate_impact": 0.858,
        "error_rate_ratio": 0.058
    },
    {
        "id": 70,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l1']",
        "acc": 0.72,
        "precision": 0.835,
        "recall": 0.783,
        "statistical_parity_difference": -0.033,
        "equal_opportunity_difference": -0.04,
        "disparate_impact": 0.956,
        "error_rate_ratio": 0.055
    },
    {
        "id": 71,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l2']",
        "acc": 0.727,
        "precision": 0.854,
        "recall": 0.772,
        "statistical_parity_difference": -0.077,
        "equal_opportunity_difference": -0.089,
        "disparate_impact": 0.901,
        "error_rate_ratio": 0.054
    },
    {
        "id": 72,
        "tags": "['reweighing', 'DisparateImpactRemover', 'max']",
        "acc": 0.743,
        "precision": 0.867,
        "recall": 0.788,
        "statistical_parity_difference": -0.038,
        "equal_opportunity_difference": -0.095,
        "disparate_impact": 0.951,
        "error_rate_ratio": 0.114
    },
    {
        "id": 73,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.733,
        "precision": 0.84,
        "recall": 0.796,
        "statistical_parity_difference": -0.086,
        "equal_opportunity_difference": -0.111,
        "disparate_impact": 0.889,
        "error_rate_ratio": 0.083
    },
    {
        "id": 74,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.74,
        "precision": 0.851,
        "recall": 0.792,
        "statistical_parity_difference": -0.07,
        "equal_opportunity_difference": -0.094,
        "disparate_impact": 0.91,
        "error_rate_ratio": 0.067
    },
    {
        "id": 75,
        "tags": "['DisparateImpactRemover', 'l1', 'PCA3']",
        "acc": 0.731,
        "precision": 0.856,
        "recall": 0.777,
        "statistical_parity_difference": -0.102,
        "equal_opportunity_difference": -0.093,
        "disparate_impact": 0.87,
        "error_rate_ratio": 0.14
    },
    {
        "id": 76,
        "tags": "['DisparateImpactRemover', 'l1', 'PCA5']",
        "acc": 0.748,
        "precision": 0.852,
        "recall": 0.803,
        "statistical_parity_difference": -0.076,
        "equal_opportunity_difference": -0.098,
        "disparate_impact": 0.9,
        "error_rate_ratio": 0.135
    },
    {
        "id": 77,
        "tags": "['DisparateImpactRemover', 'l2', 'PCA3']",
        "acc": 0.737,
        "precision": 0.851,
        "recall": 0.795,
        "statistical_parity_difference": -0.047,
        "equal_opportunity_difference": -0.03,
        "disparate_impact": 0.941,
        "error_rate_ratio": 0.083
    },
    {
        "id": 78,
        "tags": "['DisparateImpactRemover', 'l2', 'PCA5']",
        "acc": 0.738,
        "precision": 0.865,
        "recall": 0.784,
        "statistical_parity_difference": -0.059,
        "equal_opportunity_difference": -0.035,
        "disparate_impact": 0.925,
        "error_rate_ratio": 0.096
    },
    {
        "id": 79,
        "tags": "['DisparateImpactRemover', 'max', 'PCA3']",
        "acc": 0.731,
        "precision": 0.859,
        "recall": 0.78,
        "statistical_parity_difference": -0.106,
        "equal_opportunity_difference": -0.073,
        "disparate_impact": 0.869,
        "error_rate_ratio": 0.077
    },
    {
        "id": 80,
        "tags": "['DisparateImpactRemover', 'max', 'PCA5']",
        "acc": 0.717,
        "precision": 0.853,
        "recall": 0.763,
        "statistical_parity_difference": -0.066,
        "equal_opportunity_difference": -0.065,
        "disparate_impact": 0.916,
        "error_rate_ratio": 0.121
    },
    {
        "id": 81,
        "tags": "['DisparateImpactRemover', 'l1', 'reweighing']",
        "acc": 0.739,
        "precision": 0.864,
        "recall": 0.784,
        "statistical_parity_difference": -0.046,
        "equal_opportunity_difference": -0.075,
        "disparate_impact": 0.941,
        "error_rate_ratio": 0.052
    },
    {
        "id": 82,
        "tags": "['DisparateImpactRemover', 'l2', 'reweighing']",
        "acc": 0.753,
        "precision": 0.862,
        "recall": 0.799,
        "statistical_parity_difference": -0.028,
        "equal_opportunity_difference": -0.038,
        "disparate_impact": 0.964,
        "error_rate_ratio": 0.03
    },
    {
        "id": 83,
        "tags": "['DisparateImpactRemover', 'max', 'reweighing']",
        "acc": 0.731,
        "precision": 0.849,
        "recall": 0.785,
        "statistical_parity_difference": -0.134,
        "equal_opportunity_difference": -0.164,
        "disparate_impact": 0.828,
        "error_rate_ratio": 0.111
    },
    {
        "id": 84,
        "tags": "['DisparateImpactRemover', 'PCA3', 'l1']",
        "acc": 0.713,
        "precision": 0.839,
        "recall": 0.768,
        "statistical_parity_difference": -0.072,
        "equal_opportunity_difference": -0.055,
        "disparate_impact": 0.91,
        "error_rate_ratio": 0.114
    },
    {
        "id": 85,
        "tags": "['DisparateImpactRemover', 'PCA3', 'l2']",
        "acc": 0.724,
        "precision": 0.814,
        "recall": 0.801,
        "statistical_parity_difference": -0.1,
        "equal_opportunity_difference": -0.096,
        "disparate_impact": 0.866,
        "error_rate_ratio": 0.108
    },
    {
        "id": 86,
        "tags": "['DisparateImpactRemover', 'PCA3', 'max']",
        "acc": 0.749,
        "precision": 0.861,
        "recall": 0.799,
        "statistical_parity_difference": -0.111,
        "equal_opportunity_difference": -0.081,
        "disparate_impact": 0.858,
        "error_rate_ratio": 0.081
    },
    {
        "id": 87,
        "tags": "['DisparateImpactRemover', 'PCA5', 'l1']",
        "acc": 0.738,
        "precision": 0.86,
        "recall": 0.786,
        "statistical_parity_difference": -0.087,
        "equal_opportunity_difference": -0.076,
        "disparate_impact": 0.891,
        "error_rate_ratio": 0.129
    },
    {
        "id": 88,
        "tags": "['DisparateImpactRemover', 'PCA5', 'l2']",
        "acc": 0.727,
        "precision": 0.845,
        "recall": 0.78,
        "statistical_parity_difference": -0.109,
        "equal_opportunity_difference": -0.107,
        "disparate_impact": 0.86,
        "error_rate_ratio": 0.134
    },
    {
        "id": 89,
        "tags": "['DisparateImpactRemover', 'PCA5', 'max']",
        "acc": 0.715,
        "precision": 0.818,
        "recall": 0.787,
        "statistical_parity_difference": -0.11,
        "equal_opportunity_difference": -0.104,
        "disparate_impact": 0.852,
        "error_rate_ratio": 0.144
    },
    {
        "id": 90,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l1']",
        "acc": 0.744,
        "precision": 0.864,
        "recall": 0.792,
        "statistical_parity_difference": -0.043,
        "equal_opportunity_difference": -0.089,
        "disparate_impact": 0.946,
        "error_rate_ratio": 0.061
    },
    {
        "id": 91,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l2']",
        "acc": 0.737,
        "precision": 0.85,
        "recall": 0.785,
        "statistical_parity_difference": -0.103,
        "equal_opportunity_difference": -0.145,
        "disparate_impact": 0.864,
        "error_rate_ratio": 0.097
    },
    {
        "id": 92,
        "tags": "['DisparateImpactRemover', 'reweighing', 'max']",
        "acc": 0.752,
        "precision": 0.862,
        "recall": 0.802,
        "statistical_parity_difference": -0.058,
        "equal_opportunity_difference": -0.113,
        "disparate_impact": 0.926,
        "error_rate_ratio": 0.12
    },
    {
        "id": 93,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA3']",
        "acc": 0.734,
        "precision": 0.827,
        "recall": 0.805,
        "statistical_parity_difference": -0.065,
        "equal_opportunity_difference": -0.084,
        "disparate_impact": 0.914,
        "error_rate_ratio": 0.053
    },
    {
        "id": 94,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA5']",
        "acc": 0.701,
        "precision": 0.823,
        "recall": 0.754,
        "statistical_parity_difference": -0.074,
        "equal_opportunity_difference": -0.12,
        "disparate_impact": 0.901,
        "error_rate_ratio": 0.092
    },
    {
        "id": 95,
        "tags": "['l1', 'reweighing', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.725,
        "precision": 0.845,
        "recall": 0.776,
        "statistical_parity_difference": -0.026,
        "equal_opportunity_difference": -0.046,
        "disparate_impact": 0.966,
        "error_rate_ratio": 0.03
    },
    {
        "id": 96,
        "tags": "['l1', 'reweighing', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.729,
        "precision": 0.859,
        "recall": 0.772,
        "statistical_parity_difference": -0.043,
        "equal_opportunity_difference": -0.079,
        "disparate_impact": 0.945,
        "error_rate_ratio": 0.06
    },
    {
        "id": 97,
        "tags": "['l2', 'reweighing', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.735,
        "precision": 0.85,
        "recall": 0.786,
        "statistical_parity_difference": -0.079,
        "equal_opportunity_difference": -0.161,
        "disparate_impact": 0.899,
        "error_rate_ratio": 0.124
    },
    {
        "id": 98,
        "tags": "['l2', 'reweighing', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.724,
        "precision": 0.85,
        "recall": 0.777,
        "statistical_parity_difference": -0.106,
        "equal_opportunity_difference": -0.141,
        "disparate_impact": 0.864,
        "error_rate_ratio": 0.074
    },
    {
        "id": 99,
        "tags": "['max', 'reweighing', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.726,
        "precision": 0.854,
        "recall": 0.772,
        "statistical_parity_difference": -0.083,
        "equal_opportunity_difference": -0.102,
        "disparate_impact": 0.895,
        "error_rate_ratio": 0.049
    },
    {
        "id": 100,
        "tags": "['max', 'reweighing', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.747,
        "precision": 0.869,
        "recall": 0.794,
        "statistical_parity_difference": -0.024,
        "equal_opportunity_difference": -0.044,
        "disparate_impact": 0.968,
        "error_rate_ratio": 0.033
    },
    {
        "id": 101,
        "tags": "['l1', 'DisparateImpactRemover', 'reweighing', 'PCA3']",
        "acc": 0.728,
        "precision": 0.851,
        "recall": 0.779,
        "statistical_parity_difference": -0.128,
        "equal_opportunity_difference": -0.151,
        "disparate_impact": 0.838,
        "error_rate_ratio": 0.109
    },
    {
        "id": 102,
        "tags": "['l1', 'DisparateImpactRemover', 'reweighing', 'PCA5']",
        "acc": 0.718,
        "precision": 0.826,
        "recall": 0.789,
        "statistical_parity_difference": -0.01,
        "equal_opportunity_difference": -0.048,
        "disparate_impact": 0.989,
        "error_rate_ratio": 0.056
    },
    {
        "id": 103,
        "tags": "['l2', 'DisparateImpactRemover', 'reweighing', 'PCA3']",
        "acc": 0.736,
        "precision": 0.836,
        "recall": 0.798,
        "statistical_parity_difference": -0.103,
        "equal_opportunity_difference": -0.091,
        "disparate_impact": 0.863,
        "error_rate_ratio": 0.02
    },
    {
        "id": 104,
        "tags": "['l2', 'DisparateImpactRemover', 'reweighing', 'PCA5']",
        "acc": 0.727,
        "precision": 0.834,
        "recall": 0.786,
        "statistical_parity_difference": -0.098,
        "equal_opportunity_difference": -0.137,
        "disparate_impact": 0.868,
        "error_rate_ratio": 0.08
    },
    {
        "id": 105,
        "tags": "['max', 'DisparateImpactRemover', 'reweighing', 'PCA3']",
        "acc": 0.717,
        "precision": 0.856,
        "recall": 0.764,
        "statistical_parity_difference": -0.032,
        "equal_opportunity_difference": -0.077,
        "disparate_impact": 0.959,
        "error_rate_ratio": 0.088
    },
    {
        "id": 106,
        "tags": "['max', 'DisparateImpactRemover', 'reweighing', 'PCA5']",
        "acc": 0.731,
        "precision": 0.84,
        "recall": 0.79,
        "statistical_parity_difference": -0.054,
        "equal_opportunity_difference": -0.068,
        "disparate_impact": 0.928,
        "error_rate_ratio": 0.032
    },
    {
        "id": 107,
        "tags": "['reweighing', 'l1', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.728,
        "precision": 0.833,
        "recall": 0.792,
        "statistical_parity_difference": -0.077,
        "equal_opportunity_difference": -0.122,
        "disparate_impact": 0.897,
        "error_rate_ratio": 0.085
    },
    {
        "id": 108,
        "tags": "['reweighing', 'l1', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.743,
        "precision": 0.869,
        "recall": 0.787,
        "statistical_parity_difference": -0.105,
        "equal_opportunity_difference": -0.11,
        "disparate_impact": 0.868,
        "error_rate_ratio": 0.059
    },
    {
        "id": 109,
        "tags": "['reweighing', 'l2', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.733,
        "precision": 0.854,
        "recall": 0.783,
        "statistical_parity_difference": -0.091,
        "equal_opportunity_difference": -0.141,
        "disparate_impact": 0.884,
        "error_rate_ratio": 0.098
    },
    {
        "id": 110,
        "tags": "['reweighing', 'l2', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.735,
        "precision": 0.846,
        "recall": 0.791,
        "statistical_parity_difference": -0.058,
        "equal_opportunity_difference": -0.074,
        "disparate_impact": 0.926,
        "error_rate_ratio": 0.048
    },
    {
        "id": 111,
        "tags": "['reweighing', 'max', 'DisparateImpactRemover', 'PCA3']",
        "acc": 0.729,
        "precision": 0.836,
        "recall": 0.787,
        "statistical_parity_difference": -0.071,
        "equal_opportunity_difference": -0.139,
        "disparate_impact": 0.907,
        "error_rate_ratio": 0.104
    },
    {
        "id": 112,
        "tags": "['reweighing', 'max', 'DisparateImpactRemover', 'PCA5']",
        "acc": 0.724,
        "precision": 0.834,
        "recall": 0.781,
        "statistical_parity_difference": -0.062,
        "equal_opportunity_difference": -0.089,
        "disparate_impact": 0.916,
        "error_rate_ratio": 0.058
    },
    {
        "id": 113,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l1', 'PCA3']",
        "acc": 0.752,
        "precision": 0.849,
        "recall": 0.816,
        "statistical_parity_difference": -0.083,
        "equal_opportunity_difference": -0.102,
        "disparate_impact": 0.892,
        "error_rate_ratio": 0.066
    },
    {
        "id": 114,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l1', 'PCA5']",
        "acc": 0.739,
        "precision": 0.865,
        "recall": 0.781,
        "statistical_parity_difference": -0.067,
        "equal_opportunity_difference": -0.086,
        "disparate_impact": 0.916,
        "error_rate_ratio": 0.054
    },
    {
        "id": 115,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l2', 'PCA3']",
        "acc": 0.721,
        "precision": 0.836,
        "recall": 0.777,
        "statistical_parity_difference": -0.062,
        "equal_opportunity_difference": -0.11,
        "disparate_impact": 0.919,
        "error_rate_ratio": 0.087
    },
    {
        "id": 116,
        "tags": "['reweighing', 'DisparateImpactRemover', 'l2', 'PCA5']",
        "acc": 0.75,
        "precision": 0.867,
        "recall": 0.794,
        "statistical_parity_difference": -0.067,
        "equal_opportunity_difference": -0.055,
        "disparate_impact": 0.914,
        "error_rate_ratio": 0.017
    },
    {
        "id": 117,
        "tags": "['reweighing', 'DisparateImpactRemover', 'max', 'PCA3']",
        "acc": 0.746,
        "precision": 0.842,
        "recall": 0.813,
        "statistical_parity_difference": -0.04,
        "equal_opportunity_difference": -0.109,
        "disparate_impact": 0.946,
        "error_rate_ratio": 0.098
    },
    {
        "id": 118,
        "tags": "['reweighing', 'DisparateImpactRemover', 'max', 'PCA5']",
        "acc": 0.729,
        "precision": 0.836,
        "recall": 0.788,
        "statistical_parity_difference": -0.063,
        "equal_opportunity_difference": -0.093,
        "disparate_impact": 0.919,
        "error_rate_ratio": 0.08
    },
    {
        "id": 119,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA3', 'l1']",
        "acc": 0.723,
        "precision": 0.841,
        "recall": 0.777,
        "statistical_parity_difference": -0.117,
        "equal_opportunity_difference": -0.177,
        "disparate_impact": 0.847,
        "error_rate_ratio": 0.118
    },
    {
        "id": 120,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA3', 'l2']",
        "acc": 0.746,
        "precision": 0.868,
        "recall": 0.792,
        "statistical_parity_difference": -0.035,
        "equal_opportunity_difference": -0.055,
        "disparate_impact": 0.957,
        "error_rate_ratio": 0.047
    },
    {
        "id": 121,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA3', 'max']",
        "acc": 0.747,
        "precision": 0.854,
        "recall": 0.803,
        "statistical_parity_difference": -0.134,
        "equal_opportunity_difference": -0.164,
        "disparate_impact": 0.833,
        "error_rate_ratio": 0.105
    },
    {
        "id": 122,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA5', 'l1']",
        "acc": 0.747,
        "precision": 0.872,
        "recall": 0.793,
        "statistical_parity_difference": -0.068,
        "equal_opportunity_difference": -0.094,
        "disparate_impact": 0.915,
        "error_rate_ratio": 0.078
    },
    {
        "id": 123,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA5', 'l2']",
        "acc": 0.732,
        "precision": 0.849,
        "recall": 0.782,
        "statistical_parity_difference": -0.074,
        "equal_opportunity_difference": -0.141,
        "disparate_impact": 0.901,
        "error_rate_ratio": 0.112
    },
    {
        "id": 124,
        "tags": "['reweighing', 'DisparateImpactRemover', 'PCA5', 'max']",
        "acc": 0.718,
        "precision": 0.837,
        "recall": 0.783,
        "statistical_parity_difference": -0.092,
        "equal_opportunity_difference": -0.141,
        "disparate_impact": 0.881,
        "error_rate_ratio": 0.097
    },
    {
        "id": 125,
        "tags": "['DisparateImpactRemover', 'l1', 'reweighing', 'PCA3']",
        "acc": 0.727,
        "precision": 0.845,
        "recall": 0.78,
        "statistical_parity_difference": -0.032,
        "equal_opportunity_difference": -0.061,
        "disparate_impact": 0.958,
        "error_rate_ratio": 0.069
    },
    {
        "id": 126,
        "tags": "['DisparateImpactRemover', 'l1', 'reweighing', 'PCA5']",
        "acc": 0.735,
        "precision": 0.851,
        "recall": 0.788,
        "statistical_parity_difference": -0.084,
        "equal_opportunity_difference": -0.107,
        "disparate_impact": 0.891,
        "error_rate_ratio": 0.086
    },
    {
        "id": 127,
        "tags": "['DisparateImpactRemover', 'l2', 'reweighing', 'PCA3']",
        "acc": 0.745,
        "precision": 0.852,
        "recall": 0.796,
        "statistical_parity_difference": -0.064,
        "equal_opportunity_difference": -0.086,
        "disparate_impact": 0.916,
        "error_rate_ratio": 0.052
    },
    {
        "id": 128,
        "tags": "['DisparateImpactRemover', 'l2', 'reweighing', 'PCA5']",
        "acc": 0.749,
        "precision": 0.86,
        "recall": 0.796,
        "statistical_parity_difference": -0.043,
        "equal_opportunity_difference": -0.079,
        "disparate_impact": 0.944,
        "error_rate_ratio": 0.064
    },
    {
        "id": 129,
        "tags": "['DisparateImpactRemover', 'max', 'reweighing', 'PCA3']",
        "acc": 0.74,
        "precision": 0.834,
        "recall": 0.808,
        "statistical_parity_difference": -0.079,
        "equal_opportunity_difference": -0.083,
        "disparate_impact": 0.897,
        "error_rate_ratio": 0.042
    },
    {
        "id": 130,
        "tags": "['DisparateImpactRemover', 'max', 'reweighing', 'PCA5']",
        "acc": 0.748,
        "precision": 0.843,
        "recall": 0.811,
        "statistical_parity_difference": -0.114,
        "equal_opportunity_difference": -0.127,
        "disparate_impact": 0.85,
        "error_rate_ratio": 0.082
    },
    {
        "id": 131,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l1', 'PCA3']",
        "acc": 0.741,
        "precision": 0.864,
        "recall": 0.783,
        "statistical_parity_difference": -0.074,
        "equal_opportunity_difference": -0.121,
        "disparate_impact": 0.903,
        "error_rate_ratio": 0.105
    },
    {
        "id": 132,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l1', 'PCA5']",
        "acc": 0.741,
        "precision": 0.836,
        "recall": 0.801,
        "statistical_parity_difference": -0.046,
        "equal_opportunity_difference": -0.103,
        "disparate_impact": 0.938,
        "error_rate_ratio": 0.088
    },
    {
        "id": 133,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l2', 'PCA3']",
        "acc": 0.737,
        "precision": 0.851,
        "recall": 0.791,
        "statistical_parity_difference": -0.1,
        "equal_opportunity_difference": -0.104,
        "disparate_impact": 0.876,
        "error_rate_ratio": 0.042
    },
    {
        "id": 134,
        "tags": "['DisparateImpactRemover', 'reweighing', 'l2', 'PCA5']",
        "acc": 0.734,
        "precision": 0.862,
        "recall": 0.783,
        "statistical_parity_difference": -0.073,
        "equal_opportunity_difference": -0.08,
        "disparate_impact": 0.909,
        "error_rate_ratio": 0.031
    },
    {
        "id": 135,
        "tags": "['DisparateImpactRemover', 'reweighing', 'max', 'PCA3']",
        "acc": 0.741,
        "precision": 0.851,
        "recall": 0.796,
        "statistical_parity_difference": -0.05,
        "equal_opportunity_difference": -0.068,
        "disparate_impact": 0.933,
        "error_rate_ratio": 0.056
    },
    {
        "id": 136,
        "tags": "['DisparateImpactRemover', 'reweighing', 'max', 'PCA5']",
        "acc": 0.727,
        "precision": 0.837,
        "recall": 0.787,
        "statistical_parity_difference": -0.075,
        "equal_opportunity_difference": -0.106,
        "disparate_impact": 0.901,
        "error_rate_ratio": 0.068
    },
    {
        "id": 137,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA3', 'l1']",
        "acc": 0.724,
        "precision": 0.844,
        "recall": 0.781,
        "statistical_parity_difference": -0.104,
        "equal_opportunity_difference": -0.143,
        "disparate_impact": 0.866,
        "error_rate_ratio": 0.087
    },
    {
        "id": 138,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA3', 'l2']",
        "acc": 0.743,
        "precision": 0.857,
        "recall": 0.799,
        "statistical_parity_difference": -0.055,
        "equal_opportunity_difference": -0.079,
        "disparate_impact": 0.929,
        "error_rate_ratio": 0.033
    },
    {
        "id": 139,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA3', 'max']",
        "acc": 0.725,
        "precision": 0.879,
        "recall": 0.753,
        "statistical_parity_difference": -0.011,
        "equal_opportunity_difference": -0.057,
        "disparate_impact": 0.987,
        "error_rate_ratio": 0.047
    },
    {
        "id": 140,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA5', 'l1']",
        "acc": 0.747,
        "precision": 0.862,
        "recall": 0.796,
        "statistical_parity_difference": -0.077,
        "equal_opportunity_difference": -0.101,
        "disparate_impact": 0.901,
        "error_rate_ratio": 0.061
    },
    {
        "id": 141,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA5', 'l2']",
        "acc": 0.733,
        "precision": 0.85,
        "recall": 0.779,
        "statistical_parity_difference": -0.063,
        "equal_opportunity_difference": -0.103,
        "disparate_impact": 0.918,
        "error_rate_ratio": 0.095
    },
    {
        "id": 142,
        "tags": "['DisparateImpactRemover', 'reweighing', 'PCA5', 'max']",
        "acc": 0.737,
        "precision": 0.845,
        "recall": 0.796,
        "statistical_parity_difference": -0.069,
        "equal_opportunity_difference": -0.123,
        "disparate_impact": 0.911,
        "error_rate_ratio": 0.107
    }
]

export default ruleItemsData;